name: Run integration tests

on:
  workflow_dispatch:
  schedule:
    # run at minute 30 past every 3rd hour
    - cron: '30 */3 * * *'

jobs:
  script:
    name: Run integration test
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Set up Python (3.11)
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'poetry'
          cache-dependency-path: poetry.lock

      - name: Install dependencies & library
        run: poetry install --no-interaction

      - name: Run test
        run: poetry run python -m tests.v4.integration
