name: Test different dependency versions

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    name: Test dependency combination
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.11", "3.12"]
        aiohttp: ["3.9"]
        pydantic: ["2.4", "2.5", "2.6"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies & library
        run: |
          poetry install --no-interaction
          poetry add aiohttp=~${{ matrix.aiohttp }} --extras="speedups" --python="<=${{ matrix.python }}" --no-interaction
          poetry add pydantic=~${{ matrix.pydantic }} --python="<=${{ matrix.python }}" --no-interaction

      - name: Test with pytest
        run: poetry run pytest -vv
